import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          type="text/css"
          href="https://fonts.googleapis.com/css?family=PT+Serif|Open+Sans:300,400,600,700,800"
        />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="%PUBLIC_URL%/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          href="%PUBLIC_URL%/favicon-32x32.png"
          sizes="32x32"
        />
        <link
          rel="icon"
          type="image/png"
          href="%PUBLIC_URL%/favicon-16x16.png"
          sizes="16x16"
        />
        <link
          rel="mask-icon"
          href="%PUBLIC_URL%/safari-pinned-tab.svg"
          color="#5bbad5"
        />
        <link rel="shortcut icon" href="%PUBLIC_URL%/favicon.ico" sizes="any" />
        <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
        <meta name="description" content="A simple note taking app" />
        <meta name="theme-color" content="#ffffff" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
